#---------------------------------------------------------------------
# frontend to OpenShift K8s API Server                                
#---------------------------------------------------------------------
frontend openshift-api-server
    bind *:6443
    default_backend openshift-api-server
    mode tcp
#---------------------------------------------------------------------
# backend to OpenShift K8s API Server                                 
#---------------------------------------------------------------------
backend openshift-api-server
    balance source
    mode tcp
#    server bootstrap  10.2.82.2:6443 check
    server master0  10.2.82.3:6443 check
    server master1  10.2.82.4:6443 check
    server master2  10.2.82.5:6443 check

#---------------------------------------------------------------------
# frontend to OpenShift Machine Config Server                         
#---------------------------------------------------------------------
frontend machine-config-server
    bind *:22623
    default_backend machine-config-server
    mode tcp
#---------------------------------------------------------------------
# backend to OpenShift Machine Config Server                          
#---------------------------------------------------------------------
backend machine-config-server
    balance source
    mode tcp
#    server bootstrap 10.2.82.2:22623 check
    server master0  10.2.82.3:22623 check
    server master1  10.2.82.4:22623 check
    server master2  10.2.82.5:22623 check

frontend ingress-http
    bind *:80
    default_backend ingress-http
    mode tcp
    option tcplog

backend ingress-http
    balance source
    mode tcp
    server worker0 10.2.82.6:80 check
    server worker1 10.2.82.7:80 check
    server worker2 10.2.82.8:80 check

frontend ingress-https
    bind *:443
    default_backend ingress-https
    mode tcp
    option tcplog

backend ingress-https
    balance source
    mode tcp
    server worker0 10.2.82.6:443 check
    server worker1 10.2.82.7:443 check
    server worker2 10.2.82.8:443 check
